version: "3.7"

services:
  app:
    image: zkan/bootstrap-signup-form:live
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
  db:
    image: postgres:9.6.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
